### ISSUE TITLE
Skin Bug 

### ISSUE THREAD

**Issue by MineSenpai** [AngelliaX/Clothes#28]
Hello, I have a Issue. The skin bends through the cosmetic. I used steve.json as a template. 
![unknown](https://user-images.githubusercontent.com/32187732/132974408-1eb0e56b-086f-42d2-abbe-e11e3bdd5359.png)
[Clothes.zip](https://github.com/TungstenVn/Clothes/files/7149106/Clothes.zip)

**Comment by JeroGamingYT** [comment]
Can you send me steve.json ?
