### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tuvqlu** [AngelliaX/Clothes#32]
![image](https://user-images.githubusercontent.com/98550458/154324863-c2f70eb1-32e8-4714-978a-cd2086264b76.jpeg)

**Comment by JeroGamingYT** [comment]
This has been fixed on the latest release v6.1 which can be found [here](https://github.com/AngelliaX/Clothes/releases/tag/v6.1)

**Comment by Tuvqlu** [comment]
Thankyou!

**Comment by Tuvqlu** [comment]
This happens: I have formapidev4.phar![image](https://user-images.githubusercontent.com/98550458/154377235-a31dacf6-f053-41ec-bbfb-d9a6660fe70a.jpeg)

**Comment by EricGamingYT** [comment]
This has been fixed on the latest release v6.2 which can be found [here](https://github.com/AngelliaX/Clothes/releases/tag/v6.2)
