### ISSUE TITLE
Crash in latest version

### ISSUE THREAD

**Issue by felipeleite5w** [AngelliaX/Clothes#34]
When I try to use clothes, it crashes when server open.

Could not check compatibility between TungstenVn\Clothes\libs\jojoe77777\FormAPI\Form::handleResponse(pocketmine\Player $player, $data): void and pocketmine\form\Form::handleResponse(pocketmine\player\Player $player, $data): void, because class pocketmine\Player is not available in phar:///home/marco/pmmp/plugins/Clothes.phar/src/TungstenVn/Clothes/libs/jojoe77777/FormAPI/Form.php on line 42

**Comment by EricGamingYT** [comment]
Dear @felipeleite5w,
> Your problem has been accepted.
Clothes v6.2 has fixed this problem please download [it here](https://github.com/AngelliaX/Clothes/releases/tag/v6.2)
