### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tuvqlu** [AngelliaX/Clothes#36]
Hello, I have a cosplay I made and it is not working, when i click on the button nothing is found. Here are the files
![trashy](https://user-images.githubusercontent.com/98550458/161868987-54750140-7825-412a-a7ac-48a6e04c6b00.png)

{
	"format_version": "1.12.0",
	"minecraft:geometry": [
		{
			"description": {
				"identifier": "geometry.cosplays/trashy",
				"texture_width": 128,
				"texture_height": 128,
				"visible_bounds_width": 3,
				"visible_bounds_height": 3.5,
				"visible_bounds_offset": [0, 1.25, 0]
			},
			"bones": [
				{
					"name": "head",
					"pivot": [0, 24, -0.5],
					"cubes": [
						{
							"origin": [-5, 24, -4.5],
							"size": [10, 9, 9],
							"uv": {
								"north": {"uv": [43, 0], "uv_size": [10, 9]},
								"east": {"uv": [40, 43], "uv_size": [9, 9]},
								"south": {"uv": [43, 9], "uv_size": [10, 9]},
								"west": {"uv": [0, 44], "uv_size": [9, 9]},
								"up": {"uv": [43, 18], "uv_size": [10, 9]},
								"down": {"uv": [30, 52], "uv_size": [10, -9]}
							}
						},
						{
							"origin": [-6, 26, -3.5],
							"size": [1, 3, 1],
							"uv": {
								"north": {"uv": [9, 44], "uv_size": [1, 3]},
								"east": {"uv": [9, 47], "uv_size": [1, 3]},
								"south": {"uv": [18, 55], "uv_size": [1, 3]},
								"west": {"uv": [8, 57], "uv_size": [1, 3]},
								"up": {"uv": [56, 10], "uv_size": [1, 1]},
								"down": {"uv": [58, 55], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [-5.75, 26.5, -2.5],
							"size": [1, 2, 1],
							"uv": {
								"north": {"uv": [57, 43], "uv_size": [1, 2]},
								"east": {"uv": [57, 45], "uv_size": [1, 2]},
								"south": {"uv": [57, 47], "uv_size": [1, 2]},
								"west": {"uv": [49, 57], "uv_size": [1, 2]},
								"up": {"uv": [59, 35], "uv_size": [1, 1]},
								"down": {"uv": [59, 44], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [4.75, 26.5, -2.5],
							"size": [1, 2, 1],
							"uv": {
								"north": {"uv": [57, 49], "uv_size": [1, 2]},
								"east": {"uv": [50, 57], "uv_size": [1, 2]},
								"south": {"uv": [51, 57], "uv_size": [1, 2]},
								"west": {"uv": [57, 51], "uv_size": [1, 2]},
								"up": {"uv": [59, 44], "uv_size": [1, 1]},
								"down": {"uv": [59, 46], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [5, 26, -3.5],
							"size": [1, 3, 1],
							"uv": {
								"north": {"uv": [15, 57], "uv_size": [1, 3]},
								"east": {"uv": [16, 57], "uv_size": [1, 3]},
								"south": {"uv": [57, 16], "uv_size": [1, 3]},
								"west": {"uv": [17, 57], "uv_size": [1, 3]},
								"up": {"uv": [59, 33], "uv_size": [1, 1]},
								"down": {"uv": [59, 35], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [-7, 28, -3.5],
							"size": [1, 1, 1],
							"uv": {
								"north": {"uv": [58, 58], "uv_size": [1, 1]},
								"east": {"uv": [59, 2], "uv_size": [1, 1]},
								"south": {"uv": [59, 3], "uv_size": [1, 1]},
								"west": {"uv": [59, 4], "uv_size": [1, 1]},
								"up": {"uv": [59, 5], "uv_size": [1, 1]},
								"down": {"uv": [6, 60], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [-7, 26, -3.5],
							"size": [1, 1, 1],
							"uv": {
								"north": {"uv": [59, 6], "uv_size": [1, 1]},
								"east": {"uv": [7, 59], "uv_size": [1, 1]},
								"south": {"uv": [59, 7], "uv_size": [1, 1]},
								"west": {"uv": [59, 10], "uv_size": [1, 1]},
								"up": {"uv": [11, 59], "uv_size": [1, 1]},
								"down": {"uv": [59, 12], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [6, 26, -3.5],
							"size": [1, 1, 1],
							"uv": {
								"north": {"uv": [12, 59], "uv_size": [1, 1]},
								"east": {"uv": [59, 12], "uv_size": [1, 1]},
								"south": {"uv": [13, 59], "uv_size": [1, 1]},
								"west": {"uv": [59, 13], "uv_size": [1, 1]},
								"up": {"uv": [14, 59], "uv_size": [1, 1]},
								"down": {"uv": [59, 15], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [6, 28, -3.5],
							"size": [1, 1, 1],
							"uv": {
								"north": {"uv": [59, 15], "uv_size": [1, 1]},
								"east": {"uv": [59, 25], "uv_size": [1, 1]},
								"south": {"uv": [59, 26], "uv_size": [1, 1]},
								"west": {"uv": [59, 28], "uv_size": [1, 1]},
								"up": {"uv": [59, 29], "uv_size": [1, 1]},
								"down": {"uv": [59, 33], "uv_size": [1, -1]}
							}
						},
						{
							"origin": [-2, 26, -5.5],
							"size": [4, 2, 1],
							"uv": {
								"north": {"uv": [54, 40], "uv_size": [4, 2]},
								"east": {"uv": [51, 31], "uv_size": [1, 2]},
								"south": {"uv": [11, 55], "uv_size": [4, 2]},
								"west": {"uv": [57, 23], "uv_size": [1, 2]},
								"up": {"uv": [56, 8], "uv_size": [4, 1]},
								"down": {"uv": [56, 10], "uv_size": [4, -1]}
							}
						},
						{
							"origin": [-1, 26.75, -5.75],
							"size": [2, 1, 1],
							"uv": {
								"north": {"uv": [20, 41], "uv_size": [2, 1]},
								"east": {"uv": [9, 50], "uv_size": [1, 1]},
								"south": {"uv": [30, 42], "uv_size": [2, 1]},
								"west": {"uv": [19, 51], "uv_size": [1, 1]},
								"up": {"uv": [57, 25], "uv_size": [2, 1]},
								"down": {"uv": [57, 27], "uv_size": [2, -1]}
							}
						},
						{
							"origin": [-4, 33, -3.5],
							"size": [8, 1, 7],
							"uv": {
								"north": {"uv": [43, 31], "uv_size": [8, 1]},
								"east": {"uv": [56, 0], "uv_size": [7, 1]},
								"south": {"uv": [43, 32], "uv_size": [8, 1]},
								"west": {"uv": [56, 1], "uv_size": [7, 1]},
								"up": {"uv": [49, 43], "uv_size": [8, 7]},
								"down": {"uv": [49, 57], "uv_size": [8, -7]}
							}
						},
						{
							"origin": [-5, 33, -0.5],
							"size": [3, 2, 1],
							"pivot": [0, 24, -0.5],
							"rotation": [0, 0, 45],
							"uv": {
								"north": {"uv": [15, 55], "uv_size": [3, 2]},
								"east": {"uv": [52, 57], "uv_size": [1, 2]},
								"south": {"uv": [56, 2], "uv_size": [3, 2]},
								"west": {"uv": [53, 57], "uv_size": [1, 2]},
								"up": {"uv": [57, 19], "uv_size": [3, 1]},
								"down": {"uv": [57, 21], "uv_size": [3, -1]}
							}
						},
						{
							"origin": [-5, 35, -0.5],
							"size": [2, 1, 1],
							"pivot": [0, 24, -0.5],
							"rotation": [0, 0, 45],
							"uv": {
								"north": {"uv": [58, 16], "uv_size": [2, 1]},
								"east": {"uv": [49, 59], "uv_size": [1, 1]},
								"south": {"uv": [58, 17], "uv_size": [2, 1]},
								"west": {"uv": [59, 49], "uv_size": [1, 1]},
								"up": {"uv": [58, 18], "uv_size": [2, 1]},
								"down": {"uv": [58, 24], "uv_size": [2, -1]}
							}
						},
						{
							"origin": [2, 33, -0.5],
							"size": [3, 2, 1],
							"pivot": [0, 24, -0.5],
							"rotation": [0, 0, -45],
							"uv": {
								"north": {"uv": [56, 4], "uv_size": [3, 2]},
								"east": {"uv": [57, 53], "uv_size": [1, 2]},
								"south": {"uv": [56, 6], "uv_size": [3, 2]},
								"west": {"uv": [54, 57], "uv_size": [1, 2]},
								"up": {"uv": [57, 21], "uv_size": [3, 1]},
								"down": {"uv": [57, 23], "uv_size": [3, -1]}
							}
						},
						{
							"origin": [3, 35, -0.5],
							"size": [2, 1, 1],
							"pivot": [0, 24, -0.5],
							"rotation": [0, 0, -45],
							"uv": {
								"north": {"uv": [55, 57], "uv_size": [2, 1]},
								"east": {"uv": [59, 46], "uv_size": [1, 1]},
								"south": {"uv": [57, 55], "uv_size": [2, 1]},
								"west": {"uv": [59, 48], "uv_size": [1, 1]},
								"up": {"uv": [57, 56], "uv_size": [2, 1]},
								"down": {"uv": [57, 58], "uv_size": [2, -1]}
							}
						}
					]
				},
				{
					"name": "lid",
					"parent": "head",
					"pivot": [0, 19, 20],
					"rotation": [65, 0, 0],
					"cubes": [
						{
							"origin": [-5, 36, 25.75],
							"size": [10, 10, 1],
							"uv": {
								"north": {"uv": [20, 42], "uv_size": [10, 10]},
								"east": {"uv": [9, 55], "uv_size": [1, 10]},
								"south": {"uv": [42, 33], "uv_size": [10, 10]},
								"west": {"uv": [10, 55], "uv_size": [1, 10]},
								"up": {"uv": [54, 38], "uv_size": [10, 1]},
								"down": {"uv": [54, 40], "uv_size": [10, -1]}
							}
						},
						{
							"origin": [-5.25, 35.75, 25.25],
							"size": [10.5, 10.5, 1.25],
							"uv": {
								"north": {"uv": [32, 11], "uv_size": [11, 11]},
								"east": {"uv": [21, 30], "uv_size": [1, 11]},
								"south": {"uv": [32, 22], "uv_size": [11, 11]},
								"west": {"uv": [55, 0], "uv_size": [1, 11]},
								"up": {"uv": [52, 42], "uv_size": [11, 1]},
								"down": {"uv": [54, 38], "uv_size": [11, -1]}
							}
						},
						{
							"origin": [-0.5, 40, 26.75],
							"size": [1, 2, 1],
							"uv": {
								"north": {"uv": [58, 52], "uv_size": [1, 2]},
								"east": {"uv": [55, 58], "uv_size": [1, 2]},
								"south": {"uv": [56, 58], "uv_size": [1, 2]},
								"west": {"uv": [57, 58], "uv_size": [1, 2]},
								"up": {"uv": [54, 59], "uv_size": [1, 1]},
								"down": {"uv": [59, 55], "uv_size": [1, -1]}
							}
						}
					]
				},
				{
					"name": "body",
					"pivot": [0, 0, 0],
					"cubes": [
						{
							"origin": [-5, 10, -5],
							"size": [10, 14, 10],
							"uv": {
								"north": {"uv": [22, 0], "uv_size": [10, 14]},
								"east": {"uv": [22, 14], "uv_size": [10, 14]},
								"south": {"uv": [22, 28], "uv_size": [10, 14]},
								"west": {"uv": [0, 30], "uv_size": [10, 14]},
								"up": {"uv": [32, 33], "uv_size": [10, 10]},
								"down": {"uv": [10, 51], "uv_size": [10, -10]}
							}
						},
						{
							"origin": [-5.25, 9.75, -5.25],
							"size": [10.5, 14.5, 10.5],
							"uv": {
								"north": {"uv": [0, 0], "uv_size": [11, 15]},
								"east": {"uv": [11, 0], "uv_size": [11, 15]},
								"south": {"uv": [0, 15], "uv_size": [11, 15]},
								"west": {"uv": [11, 15], "uv_size": [11, 15]},
								"up": {"uv": [10, 30], "uv_size": [11, 11]},
								"down": {"uv": [32, 11], "uv_size": [11, -11]}
							}
						}
					]
				},
				{
					"name": "tail",
					"parent": "body",
					"pivot": [0, 1, -3],
					"cubes": [
						{
							"origin": [-2, 14.25, -6],
							"size": [4, 4, 10],
							"pivot": [0, 1, -3],
							"rotation": [-25, 0, 0],
							"uv": {
								"north": {"uv": [53, 11], "uv_size": [4, 4]},
								"east": {"uv": [43, 27], "uv_size": [10, 4]},
								"south": {"uv": [53, 15], "uv_size": [4, 4]},
								"west": {"uv": [9, 51], "uv_size": [10, 4]},
								"up": {"uv": [19, 52], "uv_size": [4, 10]},
								"down": {"uv": [23, 62], "uv_size": [4, -10]}
							}
						},
						{
							"origin": [-2, 14.25, 4],
							"size": [4, 4, 3],
							"pivot": [0, 1, -3],
							"rotation": [-25, 0, 0],
							"uv": {
								"north": {"uv": [53, 19], "uv_size": [4, 4]},
								"east": {"uv": [6, 53], "uv_size": [3, 4]},
								"south": {"uv": [53, 23], "uv_size": [4, 4]},
								"west": {"uv": [53, 27], "uv_size": [3, 4]},
								"up": {"uv": [54, 31], "uv_size": [4, 3]},
								"down": {"uv": [54, 37], "uv_size": [4, -3]}
							}
						}
					]
				},
				{
					"name": "leftarm",
					"pivot": [0, 0, 0],
					"cubes": [
						{
							"origin": [5, 12, -1],
							"size": [2, 11, 2],
							"uv": {
								"north": {"uv": [27, 52], "uv_size": [2, 11]},
								"east": {"uv": [29, 52], "uv_size": [2, 11]},
								"south": {"uv": [31, 52], "uv_size": [2, 11]},
								"west": {"uv": [52, 31], "uv_size": [2, 11]},
								"up": {"uv": [56, 27], "uv_size": [2, 2]},
								"down": {"uv": [56, 31], "uv_size": [2, -2]}
							}
						},
						{
							"origin": [6, 11, -1],
							"size": [1, 1, 2],
							"uv": {
								"north": {"uv": [50, 59], "uv_size": [1, 1]},
								"east": {"uv": [58, 24], "uv_size": [2, 1]},
								"south": {"uv": [59, 50], "uv_size": [1, 1]},
								"west": {"uv": [58, 27], "uv_size": [2, 1]},
								"up": {"uv": [18, 58], "uv_size": [1, 2]},
								"down": {"uv": [58, 30], "uv_size": [1, -2]}
							}
						}
					]
				},
				{
					"name": "rightarm",
					"pivot": [0, 0, 0],
					"rotation": [-180, 0, 180],
					"cubes": [
						{
							"origin": [5, 12, -1],
							"size": [2, 11, 2],
							"uv": {
								"north": {"uv": [33, 52], "uv_size": [2, 11]},
								"east": {"uv": [35, 52], "uv_size": [2, 11]},
								"south": {"uv": [37, 52], "uv_size": [2, 11]},
								"west": {"uv": [39, 52], "uv_size": [2, 11]},
								"up": {"uv": [6, 57], "uv_size": [2, 2]},
								"down": {"uv": [57, 12], "uv_size": [2, -2]}
							}
						},
						{
							"origin": [6, 11, -1],
							"size": [1, 1, 2],
							"uv": {
								"north": {"uv": [51, 59], "uv_size": [1, 1]},
								"east": {"uv": [58, 30], "uv_size": [2, 1]},
								"south": {"uv": [59, 51], "uv_size": [1, 1]},
								"west": {"uv": [58, 31], "uv_size": [2, 1]},
								"up": {"uv": [58, 32], "uv_size": [1, 2]},
								"down": {"uv": [58, 36], "uv_size": [1, -2]}
							}
						}
					]
				},
				{
					"name": "leftleg",
					"pivot": [6, 0, 0],
					"cubes": [
						{
							"origin": [2, 0, -1],
							"size": [2, 11, 2],
							"uv": {
								"north": {"uv": [0, 53], "uv_size": [2, 11]},
								"east": {"uv": [53, 0], "uv_size": [2, 11]},
								"south": {"uv": [2, 53], "uv_size": [2, 11]},
								"west": {"uv": [4, 53], "uv_size": [2, 11]},
								"up": {"uv": [13, 57], "uv_size": [2, 2]},
								"down": {"uv": [57, 16], "uv_size": [2, -2]}
							}
						},
						{
							"origin": [5.01016, -1.825, 2.05087],
							"size": [1, 1, 2],
							"pivot": [6.01016, 0, 0.00087],
							"rotation": [-92.5, 0, 90],
							"uv": {
								"north": {"uv": [53, 59], "uv_size": [1, 1]},
								"east": {"uv": [58, 41], "uv_size": [2, 1]},
								"south": {"uv": [59, 53], "uv_size": [1, 1]},
								"west": {"uv": [58, 47], "uv_size": [2, 1]},
								"up": {"uv": [58, 48], "uv_size": [1, 2]},
								"down": {"uv": [58, 52], "uv_size": [1, -2]}
							}
						}
					]
				},
				{
					"name": "rightleg",
					"pivot": [0, 0, 0],
					"cubes": [
						{
							"origin": [-4, 0, -1],
							"size": [2, 11, 2],
							"uv": {
								"north": {"uv": [41, 52], "uv_size": [2, 11]},
								"east": {"uv": [43, 52], "uv_size": [2, 11]},
								"south": {"uv": [45, 52], "uv_size": [2, 11]},
								"west": {"uv": [47, 52], "uv_size": [2, 11]},
								"up": {"uv": [11, 57], "uv_size": [2, 2]},
								"down": {"uv": [57, 14], "uv_size": [2, -2]}
							}
						},
						{
							"origin": [-0.98984, -1.825, 2.05087],
							"size": [1, 1, 2],
							"pivot": [0.01016, 0, 0.00087],
							"rotation": [-92.5, 0, 90],
							"uv": {
								"north": {"uv": [52, 59], "uv_size": [1, 1]},
								"east": {"uv": [58, 36], "uv_size": [2, 1]},
								"south": {"uv": [59, 52], "uv_size": [1, 1]},
								"west": {"uv": [58, 40], "uv_size": [2, 1]},
								"up": {"uv": [58, 43], "uv_size": [1, 2]},
								"down": {"uv": [58, 47], "uv_size": [1, -2]}
							}
						}
					]
				}
			]
		}
	]
}

**Comment by DavidGlitch04** [comment]
Image must be 64x64 and texturewidth, textureheight must be 64.
